### ISSUE TITLE
controllerChange event listener in app.vue causes havoc when private network or not https

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [185driver/pwa-app-updates#10]
Just an fyi, this line in App.vue Created event:
`navigator.serviceWorker.addEventListener("controllerchange", () => {`
will cause a vuetify app to go "snakey" and exhibit strange behaviour like clicks not working in data tables, menus not dropping down on toolbar etc if the app happens to be not localhost or not https and so service worker can't operate.

Removing that line reliably fixes this problem but of course breaks the whole thing when service workers *are* supported; but it's a big issue in cases where users run the app locally on a private network as an option rather than hosted (for example).

I'm currently trying to figure out how to work around this, it's taking forever due to a slow build process and a phone as my only test device outside my localhost; I'm guessing there is a simple way to not call this by detecting if service worker is running but haven't go there yet.  

You might consider adding a conditional to that line to fix this issue.
=-=-=-
UPDATE: well that was easy:
```
 if (navigator.serviceWorker) {
      navigator.serviceWorker.addEventListener("controllerchange", () => {
...etc...
```
Please consider updating your article and code (perhaps that guy who straight up copied your article will update his as well :) )

**Comment by 185driver** [comment]
Thank you for your suggestion!  My understanding is that PWAs require `https`, but it would not be a problem to add a service worker check to the code for those cases where service workers are not supported.

I confess I've not encountered the behavior you mention in my vuetify apps thus far, but then, I'm using `https` everywhere and only modern browsers. Is the problematic behavior you mention reproducible in a way that I could observe it?

Lol re: the copied article. I wasn't aware of that. Imitation is a form of flattery I guess.

**Comment by WhatFreshHellIsThis** [comment]
PWA's do require https, but there are a surprisingly large number of use cases where it ends up on a private network or some other issue that prevents the service worker from spooling up.  It will still work fine in that scenario except for this issue that seems to get triggered in parts of vuetify.  

In my particular case I have a great many different users globally in many different circumstances and a very large number of them will be running inside a private network so there will very often not be https and it will not be localhost which would break our application if I don't bypass the event subscription in those cases.

I test this scenario by accessing my development server from my phone and other devices on my local network by my dev station IP address (which triggers the serviceworker to stand down when it's not localhost or https) for testing which is how I ran into this in the first place which is good because if it was after release I'd have pulled a lot of hair out by now!

(I ran into the copied article trying to find yours again and searching for the event name you used which I thought would be a good unique way to find it.  someone pointed it out to the author on that page in the comments and suggested they give credit to you.)

**Comment by 185driver** [comment]
Interesting, thank you.  I've updated the article and the code snippets to check for service worker support. as suggested. I've also taken the opportunity to update the dependencies, especially vuetify v2.3+, which handles snack bar buttons a bit differently than before.

**Comment by WhatFreshHellIsThis** [comment]
FYI I also just discovered that I can simply type my own IP address instead of localhost into my browser to test a non-secure connection locally on my dev workstation (should have thought of it in the first place, makes it easy to test both secure and non-secure).  thanks again!
