### ISSUE TITLE
Uncaught TypeError: workbox.clientsClaim is not a function - Workbox v4

### ISSUE THREAD

**Issue by kasperkamperman** [185driver/pwa-app-updates#2]
I got this error ```Uncaught TypeError: workbox.clientsClaim is not a function``` after I installed Vue CLI 4. 

This implements Workbox v4. 
```workbox.clientsClaim();``` is deprecated and should become ```workbox.core.clientsClaim();```

See:
https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v3

In case someone runs in this issue.

**Comment by 185driver** [comment]
Thank you, yes, I've found that too, but given the title of the article (...Vue CLI 3) I was hesitant to change the code.

**Comment by 185driver** [comment]
I updated the `sw.js` gist in the article to show both the Vue CLI 3 and Vue CLI 4 syntax. Hopefully, that will help users avoid this issue.

**Comment by vesper8** [comment]
@185driver This is such a pain point with PWAs and a struggle for many devs.. so your package is quite appreciated. It would be fantastic if you could release a new version that is compatible with vue-cli 4 workbox 4

**Comment by 185driver** [comment]
Thanks for your suggestion. I've updated the `master` branch to reflect Vue CLI 4 use, created a separate `vue-cli-3` branch for legacy use, and updated the article to note it is Vue CLI 4 aware.

**Comment by vesper8** [comment]
Thanks! I was able to find your gists on google. Could you perhaps also link the article in the Readme? I found this repo by searching for 'pwa update' on github, I've never seen this article you speak of but would like to read it : )

**Comment by 185driver** [comment]
Well, that certainly seems like the harder way of finding this resource. Ha. I've updated the repo as suggested. The article is [here](https://medium.com/@dougallrich/give-users-control-over-app-updates-in-vue-cli-3-pwas-20453aedc1f2).
